# Generated by Django 2.2.4 on 2019-08-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='engaged',
            field=models.BooleanField(default=False),
        ),
    ]
